### PR TITLE
Add embed, sharing by URL

### PR DESCRIPTION
**Pull request by mojowen**
A few big changes additions:

 * Added an offline mode if you save a sheet to your `public/sheets` directory and run `yarn dev-local`
 * Allow sharing URLS with issue key, map, filter, and selected feature (as if you clicked on it)
 * Allows data attributes to drive issue key, map, filter, and selected feature (as if you clicked on it)
 * Share button includes a link for sharing a particular view
 * Toggle off image share for qualitative maps (it doesn't work)
 * Embed button shows a textarea with div attributes all set, for easy embedding

### CODE REVIEW

**Comment by mojowen** [comment]
@noahmanger 

Here's how to test locally with a div and data attributes:

```
  <div class="data-progress-maps" data-spreadsheet-key="1loELb4aslMLnvzdU7mMz75iz11OyDblZZSRcINnukYk" data-start-feature="101" data-start-map="house"></div>
```

With a URL:

`http://localhost:1234/#bail|state|overall|13`

If the states are not correct it should fallback gracefully

**Comment by noahmanger** [comment]
Sorry for the delay on this. It mostly works, but I'm finding that some times the Issue selection doesn't make it into the share URL.

For instance:
- I loaded it (default to Opioids)
- Changed to Cash Bail
- Clicked Share

image

**Review by noahmanger — APPROVED** [review]
Awesome stuff. This works great, just had the one issue with the issue key sometimes not being added, but feel free to merge and ship once that's fixed.

**Comment by mojowen** [comment]
Thanks for the review - I’ll get a fix then :shipit:

**Comment by mojowen** [comment]
Couldn't replicate 🤔

**Pull request merged**
